# Generated by Django 3.1.4 on 2021-01-05 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assignment', '__first__'),
        ('accounts', '0002_profile_rollno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolled',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.class'),
        ),
        migrations.AlterField(
            model_name='enrolled',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
