# Generated by Django 3.1.4 on 2021-01-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(blank=True, max_length=50, null=True),
        ),
    ]
