# Generated by Django 3.1.4 on 2021-01-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_auto_20210105_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='slug',
            field=models.SlugField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='slug',
            field=models.SlugField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=models.SlugField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='slug',
            field=models.SlugField(blank=True, max_length=11, null=True),
        ),
    ]
