# Generated by Django 3.1.4 on 2021-01-10 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_io'),
    ]

    operations = [
        migrations.RenameField(
            model_name='io',
            old_name='intput1',
            new_name='input1',
        ),
        migrations.RenameField(
            model_name='io',
            old_name='intput2',
            new_name='input2',
        ),
        migrations.RenameField(
            model_name='io',
            old_name='intput3',
            new_name='input3',
        ),
        migrations.RenameField(
            model_name='io',
            old_name='intput4',
            new_name='input4',
        ),
        migrations.RenameField(
            model_name='io',
            old_name='intput5',
            new_name='input5',
        ),
    ]
