# Generated by Django 3.1.4 on 2021-01-12 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_submission_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='memory',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='timeTaken',
        ),
    ]
