# Generated by Django 3.1.4 on 2021-01-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_auto_20210110_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestsubmission',
            name='slug',
            field=models.SlugField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='io',
            name='slug',
            field=models.SlugField(blank=True, max_length=11, null=True),
        ),
    ]
