# Generated by Django 3.1.4 on 2021-01-15 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assignment', '0004_auto_20210112_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='AverageAssignmentScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('averageScore', models.IntegerField(blank=True, default=0, null=True)),
                ('assignmentName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assignment.assignment')),
                ('className', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assignment.class')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
