# Generated by Django 3.1.4 on 2020-12-27 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0005_auto_20201218_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='class_name',
            new_name='class_slug',
        ),
    ]
