# Generated by Django 3.1.4 on 2021-01-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0006_delete_averageassignmentscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='averageScore',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
