# Generated by Django 3.1.4 on 2021-01-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0007_auto_20210110_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestsubmission',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
