# Generated by Django 3.1.4 on 2021-01-16 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0008_auto_20210116_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='average',
        ),
    ]
