# Generated by Django 3.1.4 on 2020-12-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0008_auto_20201227_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='batch',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
