# Generated by Django 3.1.4 on 2021-01-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0009_auto_20210110_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestsubmission',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
