# Generated by Django 3.1.4 on 2021-05-09 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0009_remove_question_average'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='code',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
