# Generated by Django 3.1.4 on 2021-05-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0010_submission_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='activity',
            field=models.TextField(blank=True, max_length=7000, null=True),
        ),
    ]
