# Generated by Django 3.1.4 on 2020-12-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0011_auto_20201227_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
