# Generated by Django 3.1.4 on 2021-01-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0012_auto_20210110_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestsubmission',
            name='score',
            field=models.IntegerField(blank=True),
        ),
    ]
