# Generated by Django 3.1.6 on 2021-06-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0013_auto_20210626_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='io',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
