# Generated by Django 3.1.6 on 2021-07-02 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0014_io_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='io',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.question'),
        ),
    ]
