# Generated by Django 3.1.6 on 2021-07-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0015_auto_20210702_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='io',
            name='input',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='io',
            name='output',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
