# Generated by Django 3.1.6 on 2021-07-02 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assignment', '0016_auto_20210702_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestsubmission',
            name='activity',
            field=models.TextField(blank=True, max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='bestsubmission',
            name='code',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='bestsubmission',
            name='lastRun',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bestsubmission',
            name='slug',
            field=models.SlugField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='bestsubmission',
            name='status',
            field=models.CharField(blank=True, default='Wrong', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='slug',
            field=models.SlugField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='bestsubmission',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bestsubmission',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
