# Generated by Django 3.1.6 on 2021-07-02 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0017_auto_20210702_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bestsubmission',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='bestsubmission',
            name='code',
        ),
        migrations.RemoveField(
            model_name='bestsubmission',
            name='lastRun',
        ),
        migrations.RemoveField(
            model_name='bestsubmission',
            name='question',
        ),
        migrations.RemoveField(
            model_name='bestsubmission',
            name='score',
        ),
        migrations.RemoveField(
            model_name='bestsubmission',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='bestsubmission',
            name='status',
        ),
        migrations.RemoveField(
            model_name='bestsubmission',
            name='submitted_by',
        ),
        migrations.AddField(
            model_name='bestsubmission',
            name='submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assignment.submission'),
        ),
    ]
