# Generated by Django 3.1.4 on 2021-01-10 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0018_bestsubmission_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bestsubmission',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='slug',
        ),
    ]
