# Generated by Django 3.1.6 on 2021-07-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0018_auto_20210702_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(blank=True, default='Wrong', max_length=100, null=True),
        ),
    ]
